postgres:
  image: mdillon/postgis:10
  environment:
   - POSTGRES_PASSWORD=portfolio
   - POSTGRES_USER=portfolio
   - POSTGRES_DB=portfolio
  ports:
   - "5432:5432"
  volumes:
   - /docker/portfolio/data/postgres:/var/lib/postgresql/data

redis:
  image: redis:3
  ports:
   - "6379:6379"
  volumes:
   - /docker/portfolio/data/redis:/data

portfolio:
  build: .
  # command: python3 manage.py runsslserver 0.0.0.0:8000
  command: python manage.py runserver 0.0.0.0:8000 --insecure
  volumes:
    - .:/portfolio
  ports:
    - "8000:8000"
  links:
    - postgres
